# Generated by Django 5.1.6 on 2025-02-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteuptime',
            name='uptime',
        ),
        migrations.RemoveField(
            model_name='websiteuptime',
            name='website',
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='amazon',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='apple',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='facebook',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='friendster',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='geocities',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='google',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='microsoft',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='myspace',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='netflix',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='reddit',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='twitter',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='wikipedia',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='websiteuptime',
            name='youtube',
            field=models.FloatField(default=100.0),
        ),
    ]
