# Generated by Django 5.1.4 on 2025-02-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_websiteuptime_uptime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWebsiteUptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('twitter', models.FloatField(blank=True, default=100.0, null=True)),
                ('amazon', models.FloatField(blank=True, default=100.0, null=True)),
                ('apple', models.FloatField(blank=True, default=100.0, null=True)),
                ('facebook', models.FloatField(blank=True, default=100.0, null=True)),
                ('friendster', models.FloatField(blank=True, default=100.0, null=True)),
                ('geocities', models.FloatField(blank=True, default=100.0, null=True)),
                ('google', models.FloatField(blank=True, default=100.0, null=True)),
                ('microsoft', models.FloatField(blank=True, default=100.0, null=True)),
                ('myspace', models.FloatField(blank=True, default=100.0, null=True)),
                ('netflix', models.FloatField(blank=True, default=100.0, null=True)),
                ('reddit', models.FloatField(blank=True, default=100.0, null=True)),
                ('wikipedia', models.FloatField(blank=True, default=100.0, null=True)),
                ('youtube', models.FloatField(blank=True, default=100.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyWebsiteUptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('twitter', models.FloatField(blank=True, default=100.0, null=True)),
                ('amazon', models.FloatField(blank=True, default=100.0, null=True)),
                ('apple', models.FloatField(blank=True, default=100.0, null=True)),
                ('facebook', models.FloatField(blank=True, default=100.0, null=True)),
                ('friendster', models.FloatField(blank=True, default=100.0, null=True)),
                ('geocities', models.FloatField(blank=True, default=100.0, null=True)),
                ('google', models.FloatField(blank=True, default=100.0, null=True)),
                ('microsoft', models.FloatField(blank=True, default=100.0, null=True)),
                ('myspace', models.FloatField(blank=True, default=100.0, null=True)),
                ('netflix', models.FloatField(blank=True, default=100.0, null=True)),
                ('reddit', models.FloatField(blank=True, default=100.0, null=True)),
                ('wikipedia', models.FloatField(blank=True, default=100.0, null=True)),
                ('youtube', models.FloatField(blank=True, default=100.0, null=True)),
            ],
        ),
    ]
